### ISSUE TITLE
iOS implementation

### ISSUE THREAD

**Issue by heyman333** [LinusU/react-native-webcrypto#1]
Really thank you for making this module.
When do you think iOS will be completed?

**Comment by LinusU** [comment]
Unfortunately, I'm no longer working on this module in a professional capacity, but just in my spare time.

Because of that, I'm afraid I cannot commit to a specific date, but rather it will be done when I feel like working on it ☺️

**Comment by heyman333** [comment]
Thank you for reply.
If I have a chance, I will try to contribute to your code.

**Comment by Ali-Aref** [comment]
any updates !? I need this for IOS :(
